### ISSUE TITLE
Вроде как при удалении достаточно всего лишь removed выставить в true

### ISSUE THREAD

**Issue by coursar** [jed116/layers#3]
https://github.com/jed116/layers/blob/a4dc41f4010e323c93c0416c27bc10612054b85e/src/main/java/tech/itpark/repository/UserRepositoryJDBCImpl.java#L147

**Comment by jed116** [comment]
UPDATE вроде как не удаляет а обновляет запись, а в 158-й строке я как раз и передаю boolean-параметр равный true для поля removed. Или есть другой способ что б обновить значение одной колонки в записи, не через UPDATE?
