### ISSUE TITLE
Почему в JDBC есть toLowerCase, а тут - нет?

### ISSUE THREAD

**Issue by coursar** [jed116/layers#5]
https://github.com/jed116/layers/blob/a4dc41f4010e323c93c0416c27bc10612054b85e/src/main/java/tech/itpark/repository/UserRepositoryInMemoryImpl.java#L24-L33

**Comment by jed116** [comment]
Текст ДЗ из презентации 3-го урока
В проекте Layers:
1. В Service: доделать reset
2. В Service: доделать remove
3. В Repository: реализовать не удаление, а отметку

Остальной код поэтому не трогал...
